[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["Nikita Gridinskiy <nikita.gridinskiy@gmail.com>"]
edition = "2018"

[lib]
proc-macro=true

[dependencies]
syn = "0.15.29"
quote = "0.6.11"